repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      # - id: check-case-conflict
      - id: detect-private-key
      # - id: detect-aws-credentials
      #   args: [--allow missing credentials]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
