services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      # mapping ports on your pc to the port in the container
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db # to persist data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin1
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin1@mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"

volumes:
  mongodb-data:
