FROM unityci/editor:ubuntu-2022.3.8f1-windows-mono-3.1.0

USER root

# install Java
RUN apt-get update && apt-get install -y \
    openjdk-17-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m jenkins

USER jenkins

WORKDIR /home/jenkins/