FROM jenkins/inbound-agent:latest
USER root

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    gnupg2 \
    docker.io \
    build-essential \
    libssl-dev \
    python3 \
    python3-pip \
    cppcheck \
    clang-tidy \
    php8.2 \
    php8.2-xml \
    php8.2-zip \
    php8.2-xdebug \
    php8.2-pcov \
    php8.2-mbstring \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# installing codesniffer + verification
RUN curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar \
    && curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar \
    && chmod +x phpcs.phar phpcbf.phar \
    && mv phpcs.phar /usr/local/bin/phpcs \
    && mv phpcbf.phar /usr/local/bin/phpcbf

RUN phpcs -h && phpcbf -h

# setup xdebug in php
RUN echo "zend_extension=$(find /usr/lib/php -name xdebug.so | head -n 1)" >> /etc/php/8.2/cli/php.ini \
&& echo "zend_extension=$(find /usr/lib/php -name xdebug.so | head -n 1)" >> /etc/php/8.2/apache2/php.ini \
&& echo "xdebug.mode=debug" >> /etc/php/8.2/cli/php.ini \
&& echo "xdebug.start_with_request=yes" >> /etc/php/8.2/cli/php.ini \
&& echo "xdebug.client_host=host.docker.internal" >> /etc/php/8.2/cli/php.ini \
&& echo "xdebug.client_port=9003" >> /etc/php/8.2/cli/php.ini

# installing .NET SDK 6.0
RUN apt-get update && apt-get install -y \
    && wget https://dot.net/v1/dotnet-install.sh \
    && bash dotnet-install.sh --channel 6.0 \
    && rm dotnet-install.sh

# adding .NET to PATH
ENV PATH="$PATH:/root/.dotnet"

# check if node and npm is installed
RUN node -v && npm -v

RUN npm install -g newman \
    && newman -v

# installing resharper
RUN dotnet tool install -g JetBrains.ReSharper.GlobalTools

# change back to jenkins user
USER jenkins

# set working directory
WORKDIR /home/jenkins
