FROM jenkins/inbound-agent:latest
USER root

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    gnupg2 \
    docker.io \
    build-essential \
    libssl-dev \
    python3 \
    python3-pip \
    cppcheck \
    clang-tidy \
    php \
    php-xml \
    php-zip \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

# installing codesniffer + verification
RUN curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar \
    && curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar \
    && chmod +x phpcs.phar phpcbf.phar \
    && mv phpcs.phar /usr/local/bin/phpcs \
    && mv phpcbf.phar /usr/local/bin/phpcbf

RUN phpcs -h && phpcbf -h

# installing .NET SDK 6.0
RUN apt-get update && apt-get install -y \
    wget \
    && wget https://dot.net/v1/dotnet-install.sh \
    && bash dotnet-install.sh --channel 6.0 \
    && rm dotnet-install.sh

# adding .NET to PATH
ENV PATH="$PATH:/root/.dotnet"

# install resharper static code analysis
# Run using 'jb inspectcode YourSolution.sln -o=<PathToOutputFile>' to inspect code
# Run using 'jb cleanupcode YourSolution.sln' to lint code
RUN dotnet tool install -g JetBrains.ReSharper.GlobalTools

# check if node and npm is installed
RUN node -v && npm -v

RUN npm install -g newman \
    && newman -v

# change back to jenkins user
USER jenkins

# set working directory
WORKDIR /home/jenkins
