name: C/C++ CI

# Define events that trigger the workflow
on:
  # Define what kind of action for jobs to trigger
  push:
    # Trigger for specific branches
    branches: [ "main" ]
  pull_request:
    types:    [ "closed" ]
    branches: [ "main" ]
  # Manual Trigger of jobs
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # Building using cmake
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    # Runs cmake using the makefile
    - name: find makefile and make
      run: |
        export MAKEFILE=makefile
        make -f $MAKEFILE
      # Runs any tests defined in the MAKEFILE to verify that the build is working correctly
    - name: make check
      run: make check
      # Runs a distribution check, which is used to create a distribution of the package,
      # then perform tests to ensure that it can be built and installed properly from the distribution
    - name: make distcheck
      run: |
        echo "Running distribution check..."
        make distcheck
      # tee output.log logs the output of the program
      # check if output contains <text> using grep -q <text>
    - name: run the program and check whether the output is correct
      run: |
        ./Source/main | tee output.log | grep -q "Hello, World!"
        if [ $? -ne 0 ]; then
          echo "Test failed. Closing..."
          exit 1
        fi
        echo "Test Passed..."

    


